import type {
  AppStateSaveRequest,
  AudioCropRequest,
  AudioEditRequest,
  CreateProjectRequest,
  DialogFileSelectionOptions,
  FileTreeScanOptions,
  ProjectStateLoadRequest,
  StartupSplashProgress,
  TensorBoardSessionRequest,
  VoiceModelRuntimeRequest,
  WaveformReadOptions,
  WorkspaceBatchSpeakerDiarizationRequest,
  WorkspaceCancelRequest,
  WorkspaceExportProgressEvent,
  WorkspaceExportRequest,
  WorkspaceLoadRequest,
  WorkspaceRunProgressEvent,
  WorkspaceRunRequest,
  WorkspaceRuntimeEnvironmentRequest,
} from "@shared/ipc";

export const studioBackend = {
  getAppInfo: () => window.studioBackend.getAppInfo(),
  checkAppUpdate: () => window.studioBackend.checkAppUpdate(),
  getAppUpdateState: () => window.studioBackend.getAppUpdateState(),
  installAppUpdate: () => window.studioBackend.installAppUpdate(),
  onAppUpdateState: (callback: Parameters<typeof window.studioBackend.onAppUpdateState>[0]) => window.studioBackend.onAppUpdateState(callback),
  loadAppState: () => window.studioBackend.loadAppState(),
  saveAppState: (request: AppStateSaveRequest) => window.studioBackend.saveAppState(request),
  saveAppStateSync: (request: AppStateSaveRequest) => window.studioBackend.saveAppStateSync(request),
  createProject: (request: CreateProjectRequest) => window.studioBackend.createProject(request),
  loadProjectState: (request: ProjectStateLoadRequest) => window.studioBackend.loadProjectState(request),
  updateStartupSplash: (progress: StartupSplashProgress) => window.studioBackend.updateStartupSplash(progress),
  completeStartupSplash: () => window.studioBackend.completeStartupSplash(),
  selectFolder: () => window.studioBackend.selectFolder(),
  selectFile: (options?: DialogFileSelectionOptions) => window.studioBackend.selectFile(options),
  scanPath: (path: string, options?: FileTreeScanOptions) => window.studioBackend.scanPath(path, options),
  readWaveform: (path: string, options?: number | WaveformReadOptions) => window.studioBackend.readWaveform(path, options),
  cropWave: (request: AudioCropRequest) => window.studioBackend.cropWave(request),
  editWave: (request: AudioEditRequest) => window.studioBackend.editWave(request),
  loadWorkspace: (request: WorkspaceLoadRequest) => window.studioBackend.loadWorkspace(request),
  runWorkspace: (request: WorkspaceRunRequest) => window.studioBackend.runWorkspace(request),
  checkWorkspaceRuntime: (request: WorkspaceRuntimeEnvironmentRequest) => window.studioBackend.checkWorkspaceRuntime(request),
  installWorkspaceRuntime: (request: WorkspaceRuntimeEnvironmentRequest) => window.studioBackend.installWorkspaceRuntime(request),
  checkVoiceModelRuntime: (request: VoiceModelRuntimeRequest) => window.studioBackend.checkVoiceModelRuntime(request),
  installVoiceModelRuntime: (request: VoiceModelRuntimeRequest) => window.studioBackend.installVoiceModelRuntime(request),
  listTrainingModels: (request: Parameters<typeof window.studioBackend.listTrainingModels>[0]) => window.studioBackend.listTrainingModels(request),
  startTensorBoard: (request: TensorBoardSessionRequest) => window.studioBackend.startTensorBoard(request),
  runBatchSpeakerDiarization: (request: WorkspaceBatchSpeakerDiarizationRequest) => window.studioBackend.runBatchSpeakerDiarization(request),
  onWorkspaceRunProgress: (callback: (event: WorkspaceRunProgressEvent) => void) => window.studioBackend.onWorkspaceRunProgress(callback),
  exportWorkspace: (request: WorkspaceExportRequest) => window.studioBackend.exportWorkspace(request),
  onWorkspaceExportProgress: (callback: (event: WorkspaceExportProgressEvent) => void) => window.studioBackend.onWorkspaceExportProgress(callback),
  cancelWorkspace: (request: WorkspaceCancelRequest) => window.studioBackend.cancelWorkspace(request),
};
