export const pretrainedSedModelOptions = [
  { value: "beats", label: "BEATs Strong" },
  { value: "atst_f", label: "ATST-F Strong" },
  { value: "fpasst", label: "fPaSST Strong" },
] as const;

export const whisperAsrModelOptions = [
  { value: "tiny", label: "tiny" },
  { value: "base", label: "base" },
  { value: "small", label: "small" },
  { value: "medium", label: "medium" },
  { value: "large-v1", label: "large v1" },
  { value: "large-v2", label: "large v2" },
  { value: "large-v3", label: "large v3" },
] as const;

export const wordAlignmentDeviceOptions = [
  { value: "auto", label: "Auto" },
  { value: "cuda", label: "CUDA" },
  { value: "cpu", label: "CPU" },
] as const;

export const wordAlignmentLanguageOptions = [
  { value: "ko", label: "Korean (ko)" },
  { value: "ja", label: "Japanese (ja)" },
  { value: "en", label: "English (en)" },
  { value: "zh", label: "Chinese (zh)" },
  { value: "fr", label: "French (fr)" },
  { value: "de", label: "German (de)" },
  { value: "es", label: "Spanish (es)" },
  { value: "it", label: "Italian (it)" },
  { value: "nl", label: "Dutch (nl)" },
  { value: "uk", label: "Ukrainian (uk)" },
  { value: "pt", label: "Portuguese (pt)" },
  { value: "ar", label: "Arabic (ar)" },
  { value: "cs", label: "Czech (cs)" },
  { value: "ru", label: "Russian (ru)" },
  { value: "pl", label: "Polish (pl)" },
  { value: "hu", label: "Hungarian (hu)" },
  { value: "fi", label: "Finnish (fi)" },
  { value: "fa", label: "Persian (fa)" },
  { value: "el", label: "Greek (el)" },
  { value: "tr", label: "Turkish (tr)" },
  { value: "da", label: "Danish (da)" },
  { value: "he", label: "Hebrew (he)" },
  { value: "vi", label: "Vietnamese (vi)" },
  { value: "ur", label: "Urdu (ur)" },
  { value: "te", label: "Telugu (te)" },
  { value: "hi", label: "Hindi (hi)" },
  { value: "ca", label: "Catalan (ca)" },
  { value: "ml", label: "Malayalam (ml)" },
  { value: "no", label: "Norwegian Bokmal (no)" },
  { value: "nn", label: "Norwegian Nynorsk (nn)" },
  { value: "sk", label: "Slovak (sk)" },
  { value: "sl", label: "Slovenian (sl)" },
  { value: "hr", label: "Croatian (hr)" },
  { value: "ro", label: "Romanian (ro)" },
  { value: "eu", label: "Basque (eu)" },
  { value: "gl", label: "Galician (gl)" },
  { value: "ka", label: "Georgian (ka)" },
  { value: "lv", label: "Latvian (lv)" },
  { value: "tl", label: "Tagalog (tl)" },
  { value: "sv", label: "Swedish (sv)" },
  { value: "id", label: "Indonesian (id)" },
] as const;

export const diarizenModelOptions = [
  { value: "BUT-FIT/diarizen-wavlm-large-s80-md-v2", label: "DiariZen WavLM large S80 MD v2" },
  { value: "BUT-FIT/diarizen-wavlm-large-s80-md", label: "DiariZen WavLM large S80 MD legacy" },
] as const;

export const diarizenEmbeddingModelOptions = [
  { value: "pyannote/wespeaker-voxceleb-resnet34-LM", label: "WeSpeaker ResNet34 VoxCeleb LM" },
] as const;

export const whisperLanguageOptions = [
  { value: "auto", label: "Auto (auto)" },
  { value: "af", label: "Afrikaans (af)" },
  { value: "am", label: "Amharic (am)" },
  { value: "ar", label: "Arabic (ar)" },
  { value: "as", label: "Assamese (as)" },
  { value: "az", label: "Azerbaijani (az)" },
  { value: "ba", label: "Bashkir (ba)" },
  { value: "be", label: "Belarusian (be)" },
  { value: "bg", label: "Bulgarian (bg)" },
  { value: "bn", label: "Bengali (bn)" },
  { value: "bo", label: "Tibetan (bo)" },
  { value: "br", label: "Breton (br)" },
  { value: "bs", label: "Bosnian (bs)" },
  { value: "ca", label: "Catalan (ca)" },
  { value: "cs", label: "Czech (cs)" },
  { value: "cy", label: "Welsh (cy)" },
  { value: "da", label: "Danish (da)" },
  { value: "de", label: "German (de)" },
  { value: "el", label: "Greek (el)" },
  { value: "en", label: "English (en)" },
  { value: "es", label: "Spanish (es)" },
  { value: "et", label: "Estonian (et)" },
  { value: "eu", label: "Basque (eu)" },
  { value: "fa", label: "Persian (fa)" },
  { value: "fi", label: "Finnish (fi)" },
  { value: "fo", label: "Faroese (fo)" },
  { value: "fr", label: "French (fr)" },
  { value: "gl", label: "Galician (gl)" },
  { value: "gu", label: "Gujarati (gu)" },
  { value: "ha", label: "Hausa (ha)" },
  { value: "haw", label: "Hawaiian (haw)" },
  { value: "he", label: "Hebrew (he)" },
  { value: "hi", label: "Hindi (hi)" },
  { value: "hr", label: "Croatian (hr)" },
  { value: "ht", label: "Haitian Creole (ht)" },
  { value: "hu", label: "Hungarian (hu)" },
  { value: "hy", label: "Armenian (hy)" },
  { value: "id", label: "Indonesian (id)" },
  { value: "is", label: "Icelandic (is)" },
  { value: "it", label: "Italian (it)" },
  { value: "ja", label: "Japanese (ja)" },
  { value: "jw", label: "Javanese (jw)" },
  { value: "ka", label: "Georgian (ka)" },
  { value: "kk", label: "Kazakh (kk)" },
  { value: "km", label: "Khmer (km)" },
  { value: "kn", label: "Kannada (kn)" },
  { value: "ko", label: "Korean (ko)" },
  { value: "la", label: "Latin (la)" },
  { value: "lb", label: "Luxembourgish (lb)" },
  { value: "ln", label: "Lingala (ln)" },
  { value: "lo", label: "Lao (lo)" },
  { value: "lt", label: "Lithuanian (lt)" },
  { value: "lv", label: "Latvian (lv)" },
  { value: "mg", label: "Malagasy (mg)" },
  { value: "mi", label: "Maori (mi)" },
  { value: "mk", label: "Macedonian (mk)" },
  { value: "ml", label: "Malayalam (ml)" },
  { value: "mn", label: "Mongolian (mn)" },
  { value: "mr", label: "Marathi (mr)" },
  { value: "ms", label: "Malay (ms)" },
  { value: "mt", label: "Maltese (mt)" },
  { value: "my", label: "Myanmar (my)" },
  { value: "ne", label: "Nepali (ne)" },
  { value: "nl", label: "Dutch (nl)" },
  { value: "nn", label: "Nynorsk (nn)" },
  { value: "no", label: "Norwegian (no)" },
  { value: "oc", label: "Occitan (oc)" },
  { value: "pa", label: "Punjabi (pa)" },
  { value: "pl", label: "Polish (pl)" },
  { value: "ps", label: "Pashto (ps)" },
  { value: "pt", label: "Portuguese (pt)" },
  { value: "ro", label: "Romanian (ro)" },
  { value: "ru", label: "Russian (ru)" },
  { value: "sa", label: "Sanskrit (sa)" },
  { value: "sd", label: "Sindhi (sd)" },
  { value: "si", label: "Sinhala (si)" },
  { value: "sk", label: "Slovak (sk)" },
  { value: "sl", label: "Slovenian (sl)" },
  { value: "sn", label: "Shona (sn)" },
  { value: "so", label: "Somali (so)" },
  { value: "sq", label: "Albanian (sq)" },
  { value: "sr", label: "Serbian (sr)" },
  { value: "su", label: "Sundanese (su)" },
  { value: "sv", label: "Swedish (sv)" },
  { value: "sw", label: "Swahili (sw)" },
  { value: "ta", label: "Tamil (ta)" },
  { value: "te", label: "Telugu (te)" },
  { value: "tg", label: "Tajik (tg)" },
  { value: "th", label: "Thai (th)" },
  { value: "tk", label: "Turkmen (tk)" },
  { value: "tl", label: "Tagalog (tl)" },
  { value: "tr", label: "Turkish (tr)" },
  { value: "tt", label: "Tatar (tt)" },
  { value: "uk", label: "Ukrainian (uk)" },
  { value: "ur", label: "Urdu (ur)" },
  { value: "uz", label: "Uzbek (uz)" },
  { value: "vi", label: "Vietnamese (vi)" },
  { value: "yi", label: "Yiddish (yi)" },
  { value: "yo", label: "Yoruba (yo)" },
  { value: "zh", label: "Chinese (zh)" },
  { value: "yue", label: "Cantonese (yue)" },
] as const;
