export type { AppGuideTourStep } from "./app-tour-types";
import type { AppGuideTourStep } from "./app-tour-types";

export const appTourSteps = [
  {
    id: "guide-entry",
    workspaceId: "overview",
    target: '[data-app-tour-target="guide-button"]',
    title: "가이드 모드 시작",
    caption: "공통",
    description: "GUIDE를 열면 실제 프로젝트는 건드리지 않고 화면만 가이드 샘플 상태로 바뀝니다. 닫으면 선택했던 페이지와 데이터로 돌아갑니다.",
    bullets: ["앱 설치 후 첫 접속에는 이 가이드가 자동으로 한 번만 열립니다.", "가이드 안의 버튼, 표, 로그는 실행 결과를 바꾸지 않는 미리보기입니다."],
    placement: "right",
  },
  {
    id: "workspace-nav",
    workspaceId: "overview",
    target: '[data-app-tour-target="workspace-nav"]',
    title: "왼쪽 작업 탭",
    caption: "공통",
    description: "왼쪽 탭은 Slice, Tagging, De-noise, Score, Script, Training, Inference로 이어지는 작업 흐름입니다. 가이드 중에는 설명할 페이지로 자동 이동합니다.",
    bullets: ["실제 선택 페이지는 가이드 종료 후 복원됩니다.", "실행 중인 작업이 있으면 페이지 전환보다 상태 확인을 먼저 보세요."],
    placement: "right",
  },
  {
    id: "workspace-splitters",
    workspaceId: "overview",
    target: '[data-app-tour-target="workspace-resize-line"][data-resize-orientation="vertical"]',
    title: "패널 폭과 높이 조절",
    caption: "공통",
    description: "패널 사이의 얇은 손잡이를 드래그하면 왼쪽 브라우저, 중앙 작업 영역, 오른쪽 설정 영역의 폭과 위아래 카드 높이를 조절합니다.",
    bullets: ["창이 좁으면 일부 카드는 자동으로 접히며, 다시 넓히면 내용이 돌아옵니다.", "손잡이를 잡아 움직이는 동안 표와 파형은 레이아웃이 흔들리지 않도록 잠시 고정됩니다."],
    placement: "top",
    visualCue: "panel-resize",
  },
  {
    id: "file-browser-common",
    workspaceId: "overview",
    target: '[data-app-tour-target="file-browser-section-header"]',
    title: "입력과 출력 브라우저",
    caption: "공통",
    description: "브라우저 카드는 입력 폴더와 출력 폴더를 접고 펼치며 봅니다. 폴더 경로가 길면 축약 표시되고, 파일을 고르면 표와 오디오 카드가 같은 파일로 맞춰집니다.",
    bullets: ["입력 폴더 버튼은 처리할 원본 위치를, 출력 폴더 버튼은 결과 저장 위치를 바꿉니다.", "출력 결과가 많으면 브라우저가 보이는 구간만 불러오며 스크롤 위치에 따라 이어서 로드합니다."],
    placement: "right",
  },
  {
    id: "data-grid-sheets",
    workspaceId: "overview",
    target: '[data-app-tour-target="data-grid-sheets"]',
    title: "시트와 표 상단 도구",
    caption: "공통",
    description: "표 헤더의 시트 선택, 표시 행 수, 검색, 페이지별 도구 버튼은 결과 표를 보는 기준을 바꿉니다.",
    bullets: ["시트 선택 드롭다운은 결과 묶음을 전환합니다.", "검색과 페이지별 도구 버튼은 작업 화면마다 필요한 필터나 편집 위젯을 엽니다."],
    placement: "top",
  },
  {
    id: "data-grid-selection",
    workspaceId: "overview",
    target: '[data-app-tour-target="data-grid-guide-context-row"]',
    title: "표 선택과 우클릭 메뉴",
    caption: "공통",
    description: "행을 클릭하면 해당 파일이 선택되고, Ctrl을 누른 채 클릭하면 여러 행을 동시에 선택합니다. 선택한 행은 재생 카드, 상세 카드, 브라우저 위치와 연결됩니다.",
    bullets: ["표 안을 우클릭하면 복사, 붙여넣기, 전체 선택 메뉴가 열립니다.", "체크박스는 내보내기 대상이며, 행 선택과 별개로 관리됩니다."],
    placement: "top",
    visualCue: "context-menu",
  },
  {
    id: "data-grid-resize",
    workspaceId: "overview",
    target: '[data-app-tour-target="data-grid-resize-cell"]',
    title: "표 셀 크기 조절",
    caption: "공통",
    description: "열 오른쪽 경계는 좌우로 드래그해 넓히고, 행 아래 경계는 위아래로 드래그해 높이를 조절합니다. 긴 경로나 전사문이 잘릴 때 가장 먼저 쓰는 기능입니다.",
    bullets: ["열 경계 더블클릭은 해당 열 자동 맞춤입니다.", "행 경계 더블클릭은 현재 표의 행 높이를 내용 기준으로 다시 계산합니다."],
    placement: "top",
    visualCue: "cell-resize",
  },
  {
    id: "audio-edit-common",
    workspaceId: "overview",
    target: '[data-app-tour-target="audio-edit-pane"]',
    title: "오디오 파형 편집 공통",
    caption: "공통",
    description: "재생 카드의 파형은 듣기만 하는 영역이 아니라 검수용 임시 편집 영역입니다. 드래그로 구간을 만들고, 선택 구간을 우클릭하면 자르기, 복사, 삭제, 붙여넣기를 할 수 있습니다.",
    bullets: ["휠은 파형 확대/축소이며, 선택 핸들은 좌우로 끌어 구간을 미세 조정합니다.", "편집 세션은 원본을 바로 덮어쓰지 않고 작업 상태로 쌓입니다."],
    placement: "top",
  },
  {
    id: "audio-transport-common",
    workspaceId: "overview",
    target: '[data-app-tour-target="audio-transport-controls"]',
    title: "재생 컨트롤",
    caption: "공통",
    description: "오디오 카드 아래 버튼은 5초 뒤로, 재생/정지, 5초 앞으로 이동합니다. 표나 타임라인에서 행을 바꾸면 같은 카드가 선택 파일로 갱신됩니다.",
    bullets: ["Script 타임라인처럼 동기화된 위젯은 클릭한 단어 위치로 재생 헤드를 이동시킵니다.", "짧은 구간 검수는 파형 선택과 반복 재생을 함께 쓰면 빠릅니다."],
    placement: "top",
  },
  {
    id: "run-controls",
    workspaceId: "overview",
    target: '[data-app-tour-target="run-controls"]',
    title: "실행, 재시도, 내보내기",
    caption: "공통",
    description: "NEW RUN은 현재 페이지의 입력과 설정으로 처리를 시작하고, RETRY는 실패하거나 중단된 실행을 같은 조건으로 다시 시도합니다. EXPORT는 체크된 결과만 내보냅니다.",
    bullets: ["실행 전에는 왼쪽 입력 폴더와 오른쪽 설정을 먼저 확인하세요.", "가이드 모드에서는 이 버튼들이 실제 백엔드를 실행하지 않습니다."],
    placement: "right",
  },
  {
    id: "console-button",
    workspaceId: "overview",
    target: ['[data-app-tour-target="workspace-console-button"]', '[data-app-tour-target="compact-console-pagebar"]'],
    title: "공통 콘솔 버튼",
    caption: "공통",
    description: "각 페이지 상단의 콘솔 버튼은 해당 작업의 백엔드 로그를 열고 닫습니다. 실패 원인, 모델 로드, 파일 저장 경로처럼 표에 다 안 보이는 정보는 여기서 확인합니다.",
    bullets: ["콘솔은 특정 페이지만의 기능이 아니라 모든 실행 페이지에서 쓰는 공통 기능입니다.", "오류가 나면 표 상태보다 콘솔의 마지막 에러 줄을 먼저 확인하세요."],
    placement: "left",
  },
  {
    id: "terminal-dock",
    workspaceId: "overview",
    target: '[data-app-tour-target="workspace-terminal-widget"]',
    title: "콘솔 미리보기와 전체 로그",
    caption: "공통",
    description: "콘솔 위젯은 최근 로그를 작게 보여주고, 화살표 버튼으로 전체 터미널 창을 엽니다. 긴 실행에서는 진행률보다 콘솔이 실제 작업 상태를 더 자세히 말해줍니다.",
    bullets: ["가이드 샘플 로그는 모델 로드, 분석 완료, 결과 저장 흐름을 짧게 보여줍니다.", "전체 로그 창에서는 명령, 에러, 로그 파일 경로를 함께 확인합니다."],
    placement: "left",
    terminalOpen: true,
  },
  {
    id: "slice-browser",
    workspaceId: "slice",
    target: '[data-app-tour-panel-id="slice-browser"]',
    title: "Slice 입력 파일",
    caption: "Slice",
    description: "Slice는 긴 WAV를 학습이나 검수에 맞는 짧은 조각으로 나누는 시작 페이지입니다. 왼쪽 브라우저에서 원본 파일을 고르면 중앙 에디터와 결과 표가 같은 원본을 봅니다.",
    bullets: ["입력은 긴 원본 WAV, 출력은 잘린 조각 WAV입니다.", "출력 브라우저는 실행 뒤 생성된 조각을 확인하는 위치입니다."],
    placement: "right",
  },
  {
    id: "slice-editor-header",
    workspaceId: "slice",
    target: '[data-app-tour-target="slice-editor-header-controls"]',
    focusPanelId: "slice-editor",
    title: "루프와 줌 컨트롤",
    caption: "Slice",
    description: "루프 미리보기를 켜면 선택한 조각 구간만 반복해서 들을 수 있습니다. 확대/축소 버튼과 마우스 휠은 파형을 더 촘촘하게 보거나 전체 흐름으로 되돌릴 때 씁니다.",
    bullets: ["말 앞뒤가 잘리는지 볼 때는 루프를 켜고 경계만 반복 확인하세요.", "확대 상태는 하단 미니맵의 보기 범위와 같이 움직입니다."],
    placement: "top",
  },
  {
    id: "slice-editor-waveform",
    workspaceId: "slice",
    target: '[data-app-tour-target="slice-editor-waveform"]',
    focusPanelId: "slice-editor",
    title: "마커와 선택 방식",
    caption: "Slice",
    description: "보라색 구간이 슬라이스 마커입니다. 마커 몸통을 드래그하면 구간 전체가 이동하고, 양쪽 핸들을 끌면 시작/종료 시간이 바뀝니다.",
    bullets: ["Ctrl+클릭은 여러 마커를 선택해 병합 후보로 만듭니다.", "병합된 마커 안의 조각을 고를 때는 Shift+클릭을 사용합니다."],
    placement: "top",
  },
  {
    id: "slice-editor-actions",
    workspaceId: "slice",
    target: ['[data-app-tour-target="slice-editor-actions"]', '[data-app-tour-target="slice-editor-actions-row"]'],
    focusPanelId: "slice-actions",
    title: "마커 분할과 병합",
    caption: "Slice",
    description: "마커 분할은 선택 마커를 내부 기준으로 나누거나, 이미 병합된 마커를 다시 풀 때 사용합니다. 마커 병합은 Ctrl로 여러 행/마커를 고른 뒤 하나의 조각으로 합칩니다.",
    bullets: ["병합하면 결과 표에서는 하나의 행이 되고, 내부 조각 경계는 파형 안에 점선으로 남습니다.", "마커를 우클릭하면 복사, 삭제, 분할, 선택 마커 병합 메뉴를 바로 열 수 있습니다."],
    placement: "top",
  },
  {
    id: "slice-editor-minimap",
    workspaceId: "slice",
    target: '[data-app-tour-target="slice-editor-minimap"]',
    focusPanelId: "slice-editor",
    title: "전체 파형 미니맵",
    caption: "Slice",
    description: "아래 미니맵은 긴 파일 전체에서 지금 보고 있는 구간을 나타냅니다. 선택 범위를 드래그하면 확대된 작업 구간이 이동합니다.",
    bullets: ["확대해서 경계를 고친 뒤 미니맵으로 다음 말 구간으로 빠르게 넘어갑니다.", "마우스 휠 확대와 미니맵 이동을 같이 쓰면 긴 파일 검수가 빨라집니다."],
    placement: "top",
  },
  {
    id: "slice-editor-time-grid",
    workspaceId: "slice",
    target: '[data-app-tour-target="slice-editor-time-grid"]',
    focusPanelId: "slice-editor",
    title: "시간값 확인",
    caption: "Slice",
    description: "하단 시간 그리드는 선택 마커의 시작, 종료, 길이를 숫자로 확인하는 곳입니다. 파형을 끌어 바꾼 경계가 여기에도 즉시 반영됩니다.",
    bullets: ["짧은 무음이나 말끝 누락은 시간값으로도 한 번 더 확인하세요.", "이동 버튼은 해당 경계로 재생 위치를 맞출 때 쓰는 보조 컨트롤입니다."],
    placement: "top",
  },
  {
    id: "slice-table",
    workspaceId: "slice",
    target: '[data-app-tour-panel-id="slice-results"]',
    title: "슬라이스 결과 표",
    caption: "Slice",
    description: "결과 표는 각 조각의 시작, 종료, 길이, 마커 수, 출력 경로를 기록합니다. 행 선택은 파형 선택과 브라우저 위치를 함께 바꿉니다.",
    bullets: ["체크박스는 내보낼 조각을 고르는 용도입니다.", "검색창은 파일명, 상태, 경로가 많은 프로젝트에서 빠르게 좁힐 때 씁니다."],
    placement: "top",
  },
  {
    id: "slice-settings",
    workspaceId: "slice",
    target: '[data-app-tour-panel-id="slice-settings"]',
    title: "분할 기준 설정",
    caption: "Slice",
    description: "오른쪽 설정은 침묵 길이, 패딩, 최대 조각 길이, 병합 간격처럼 결과 행 수를 직접 바꾸는 값입니다. 같은 파일도 이 값에 따라 완전히 다른 조각표가 나옵니다.",
    bullets: ["너무 잘게 쪼개지면 최소 이벤트 길이와 병합 간격을 올립니다.", "말 앞뒤가 잘리면 speech pad와 boundary search 값을 늘립니다."],
    placement: "left",
  },
  {
    id: "tagging-browser",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-browser"]',
    title: "태깅할 조각 선택",
    caption: "Tagging",
    description: "Tagging은 Slice 결과 같은 짧은 WAV를 Pretrained SED로 분석해 숨소리, 잡음, 웃음 같은 이벤트 후보를 붙입니다.",
    bullets: ["왼쪽 파일 선택은 재생 카드와 결과 표 선택을 함께 이동시킵니다.", "체크 해제된 행은 내보내기 대상에서 빠집니다."],
    placement: "right",
  },
  {
    id: "tagging-audio",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-audio"]',
    title: "태그를 귀로 확인",
    caption: "Tagging",
    description: "오디오 재생 카드는 태그가 붙은 파일을 바로 들어보는 곳입니다. 수치상 NG여도 실제로는 허용 가능한 호흡인지 여기서 판단합니다.",
    bullets: ["파형에서 의심 구간을 만들어 우클릭하면 검수용 편집을 할 수 있습니다.", "재생 카드와 표 선택은 같은 파일을 바라보도록 동기화됩니다."],
    placement: "bottom",
  },
  {
    id: "tagging-schema",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-queue"]',
    title: "스키마와 NG 기준",
    caption: "Tagging",
    description: "스키마 카드는 어떤 이벤트 태그를 NG 후보로 볼지 요약합니다. 태그 이름, 카테고리, 컷 기준이 결과 표 판단에 연결됩니다.",
    bullets: ["컷 기준을 바꾸면 같은 결과도 OK/NG 해석이 달라집니다.", "프로젝트 성격에 따라 민감한 이벤트만 남기는 것이 좋습니다."],
    placement: "top",
  },
  {
    id: "tagging-score-button",
    workspaceId: "tagging",
    target: '[data-app-tour-target="table-toolbar-tagging"]',
    title: "태그 컷 설정 열기",
    caption: "Tagging",
    description: "태깅 표 오른쪽의 리스트 버튼은 이벤트별 NG 점수 상한 위젯을 엽니다. 단순 표 필터가 아니라 태그 판정 기준 자체를 관리하는 도구입니다.",
    bullets: ["실행 후 결과가 너무 엄격하거나 느슨할 때 이 버튼을 먼저 확인합니다.", "다음 단계에서 실제 위젯을 열어 구조를 보여줍니다."],
    placement: "top",
  },
  {
    id: "tagging-score-dialog",
    workspaceId: "tagging",
    target: '[data-app-tour-target="tagging-score-dialog"]',
    title: "이벤트별 점수 위젯",
    caption: "Tagging",
    description: "이 위젯은 태그 목록을 검색하고, 카테고리별로 좁히고, 여러 태그를 체크한 뒤 일괄 수정할 수 있습니다. 적용을 누르면 Tagging 결과 해석에 쓰입니다.",
    bullets: ["자동 적용을 끄면 해당 태그는 NG 후보에서 제외됩니다.", "일괄 수정은 체크된 태그들의 컷 값을 한 번에 맞출 때 씁니다."],
    placement: "bottom",
  },
  {
    id: "tagging-table",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-results"]',
    title: "태깅 결과 표",
    caption: "Tagging",
    description: "결과 표는 파일별 주요 NG 태그, 상태, 점수 요약을 보여줍니다. 이 표는 뒤의 Score나 Script에서 검수 우선순위를 잡는 힌트가 됩니다.",
    bullets: ["행을 고르면 재생 카드와 파일 브라우저가 같은 파일로 이동합니다.", "태그가 많을수록 검색과 체크박스를 함께 써서 후보를 줄이세요."],
    placement: "top",
  },
  {
    id: "tagging-settings",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-settings"]',
    title: "SED 모델 설정",
    caption: "Tagging",
    description: "오른쪽 설정은 PretrainedSED 체크포인트, 이벤트 임계값, median window, 프레임 간격, Top K를 바꿉니다. 실행 전 기준을 정하는 곳입니다.",
    bullets: ["threshold를 낮추면 더 많이 잡고, 높이면 확실한 이벤트만 남습니다.", "median window는 짧게 튀는 오탐을 줄이는 데 도움됩니다."],
    placement: "left",
  },
  {
    id: "speaker-browser",
    workspaceId: "speaker",
    target: '[data-app-tour-panel-id="speaker-browser"]',
    title: "디노이즈 입력과 출력",
    caption: "De-noise",
    description: "De-noise는 원본과 개선 결과를 비교하는 페이지입니다. 왼쪽 브라우저에서 원본이나 출력 파일을 오가며 선택할 수 있습니다.",
    bullets: ["입력은 처리 전 음성, 출력은 모델이 생성한 개선 음성입니다.", "표에서 행을 선택하면 비교 카드가 같은 파일 쌍으로 맞춰집니다."],
    placement: "right",
  },
  {
    id: "speaker-progress",
    workspaceId: "speaker",
    target: '[data-app-tour-panel-id="speaker-progress"]',
    title: "처리 진행 표",
    caption: "De-noise",
    description: "진행 표는 파일별 모델, 상태, 출력 경로, 실패 여부를 보여줍니다. 완료된 행은 바로 아래 비교 카드에서 들어볼 수 있습니다.",
    bullets: ["실패한 행은 공통 RETRY 흐름으로 다시 처리합니다.", "처리 모델이 다르면 같은 입력도 결과 음색이 달라질 수 있습니다."],
    placement: "top",
  },
  {
    id: "speaker-comparison",
    workspaceId: "speaker",
    target: '[data-app-tour-panel-id="speaker-audio-comparison"]',
    title: "원본과 결과 비교",
    caption: "De-noise",
    description: "왼쪽은 원본, 오른쪽은 개선 결과입니다. 같은 행 기준으로 재생 위치를 맞춰 잡음 감소와 음색 손상을 비교합니다.",
    bullets: ["짧은 구간을 만들어 반복 청취하면 차이를 빠르게 판단할 수 있습니다.", "결과가 과하게 뭉개지면 오른쪽 모델이나 청크 설정을 바꿔 재실행합니다."],
    placement: "top",
  },
  {
    id: "speaker-model",
    workspaceId: "speaker",
    target: '[data-app-tour-panel-id="speaker-model"]',
    title: "복원 모델 선택",
    caption: "De-noise",
    description: "오른쪽 위 카드에서 Sidon, Resemble Enhance, VoiceFixer 중 사용할 모델을 고릅니다. 선택한 모델에 따라 아래 설정 카드가 달라집니다.",
    bullets: ["Sidon은 복원 품질 중심, Resemble은 향상/노이즈 제거 옵션 중심입니다.", "모델 선택은 다음 실행부터 적용됩니다."],
    placement: "left",
  },
  {
    id: "speaker-settings",
    workspaceId: "speaker",
    target: '[data-app-tour-panel-id="speaker-settings"]',
    title: "모델별 세부 설정",
    caption: "De-noise",
    description: "설정 카드는 장치, 청크 길이, 패딩, 하이패스, 출력 bit depth 같은 실행 인자를 관리합니다. 긴 오디오의 경계 손상은 주로 여기서 조정합니다.",
    bullets: ["청크가 짧으면 메모리는 줄지만 경계 보정이 더 중요해집니다.", "CUDA 문제가 있으면 device를 auto나 cpu로 바꿔 원인을 좁힐 수 있습니다."],
    placement: "left",
  },
  {
    id: "overview-table",
    workspaceId: "overview",
    target: '[data-app-tour-panel-id="overview-results"]',
    title: "Score 결과 표",
    caption: "Score",
    description: "Score 표는 프로젝트 전체 파일의 길이, 샘플레이트, DNSMOS 계열 점수, 상태를 모아 보여줍니다. 검수 우선순위를 정하는 중심 표입니다.",
    bullets: ["점수 컬럼의 작은 메뉴로 OK/NG/커스텀 필터를 빠르게 걸 수 있습니다.", "행 선택은 오디오 카드와 오른쪽 상세값을 같은 파일로 맞춥니다."],
    placement: "top",
  },
  {
    id: "overview-filter-button",
    workspaceId: "overview",
    target: '[data-app-tour-target="table-toolbar-overview"]',
    title: "커스텀 필터 버튼",
    caption: "Score",
    description: "Score 표 오른쪽 필터 버튼은 기본 점수 필터와 커스텀 칩 편집기를 엽니다. 표를 보는 방식만 바꾸는 것이 아니라 검수 기준 묶음을 저장할 수 있습니다.",
    bullets: ["예: BAK 낮음 + OVRL 낮음 같은 조건을 칩으로 저장합니다.", "다음 단계에서 실제 필터 위젯을 열어 설명합니다."],
    placement: "top",
  },
  {
    id: "overview-filter-dialog",
    workspaceId: "overview",
    target: '[data-app-tour-target="overview-filter-dialog"]',
    title: "필터 규칙 위젯",
    caption: "Score",
    description: "이 위젯에서는 기본 필터와 커스텀 칩을 관리합니다. 커스텀 칩은 여러 점수 조건을 이름 붙여 저장하고, 표 컬럼 메뉴에서 다시 사용할 수 있습니다.",
    bullets: ["기본 필터는 빠른 OK/NG 분류에 좋습니다.", "커스텀 칩은 프로젝트별 검수 기준을 반복 적용할 때 유용합니다."],
    placement: "bottom",
  },
  {
    id: "overview-audio",
    workspaceId: "overview",
    target: '[data-app-tour-panel-id="overview-audio"]',
    title: "문제 파일 재생",
    caption: "Score",
    description: "오디오 카드는 Score 표에서 고른 파일을 들려줍니다. 수치만으로 판단하기 애매한 파일은 여기서 바로 확인합니다.",
    bullets: ["공통 파형 편집처럼 임시 구간을 만들고 우클릭 편집을 할 수 있습니다.", "점수와 실제 청감이 다르면 프로젝트 기준을 조정하세요."],
    placement: "top",
  },
  {
    id: "overview-modules",
    workspaceId: "overview",
    target: '[data-app-tour-panel-id="overview-modules"]',
    title: "분석 모듈 선택",
    caption: "Score",
    description: "오른쪽 위 카드에서는 실행할 분석 모듈을 켜고 끕니다. 현재는 노이즈 점수 모듈이 표의 BAK, SIG, OVRL, P808 값을 만듭니다.",
    bullets: ["모듈을 끄면 다음 RUN에서 해당 분석은 수행하지 않습니다.", "최소 한 개 이상의 분석 작업이 켜져 있어야 실행 의미가 있습니다."],
    placement: "left",
  },
  {
    id: "overview-detail",
    workspaceId: "overview",
    target: '[data-app-tour-panel-id="overview-detail"]',
    title: "상세 점수와 모델 설정",
    caption: "Score",
    description: "오른쪽 아래 카드는 선택 파일의 원본 경로와 점수 원값, 그리고 DNSMOS 실행 설정을 확인하는 곳입니다.",
    bullets: ["sample rate, threads, CUDA 필수 여부는 다음 실행에 영향을 줍니다.", "선택 행이 바뀌면 상세값도 즉시 바뀝니다."],
    placement: "left",
  },
  {
    id: "batch-table",
    workspaceId: "batch",
    target: '[data-app-tour-panel-id="batch-table"]',
    title: "스크립트 편집 표",
    caption: "Script",
    description: "Script 표는 자동 전사, 편집 전사, 화자, 검수 상태를 함께 보여줍니다. 편집 전사를 바꾸면 내보내기 데이터셋에도 반영됩니다.",
    bullets: ["자동 전사 칩 색상은 정렬 점수와 누락 의심 구간을 나타냅니다.", "Ctrl+클릭으로 여러 행을 선택해 복사나 체크 작업을 묶을 수 있습니다."],
    placement: "top",
  },
  {
    id: "batch-replace-button",
    workspaceId: "batch",
    target: '[data-app-tour-target="table-toolbar-batch"]',
    title: "검색 및 바꾸기 열기",
    caption: "Script",
    description: "Script 표 오른쪽 버튼은 내용 검색 및 바꾸기 위젯을 엽니다. 전사 텍스트를 한 행씩 고치는 대신 조건에 맞는 행을 묶어 수정할 수 있습니다.",
    bullets: ["현재 화면, 체크된 행, 표시 내용 범위를 따로 지정할 수 있습니다.", "다음 단계에서 실제 바꾸기 위젯을 열어 보여줍니다."],
    placement: "top",
  },
  {
    id: "batch-replace-dialog",
    workspaceId: "batch",
    target: '[data-app-tour-target="batch-replace-dialog"]',
    title: "내용 검색 및 바꾸기 위젯",
    caption: "Script",
    description: "왼쪽에서 검색어, 바꿀 내용, 범위, 대소문자, 전체 단어 일치, 타임라인 점수 조건을 정하고 오른쪽에서 적용 후보를 확인합니다.",
    bullets: ["일괄 수정은 체크된 결과를 한 번에 바꿉니다.", "개별 수정 모드에서는 후보 행마다 적용 버튼으로 검수하며 바꿉니다."],
    placement: "bottom",
  },
  {
    id: "batch-timeline",
    workspaceId: "batch",
    target: '[data-app-tour-panel-id="batch-timeline"]',
    title: "WordAlign 타임라인",
    caption: "Script",
    description: "타임라인은 단어별 시작, 종료, 점수, 메모를 보여줍니다. 낮은 점수나 빈 구간을 클릭하면 오디오가 그 시간으로 이동합니다.",
    bullets: ["단어 칩 더블클릭은 짧은 미리듣기 검수에 좋습니다.", "빈 구간은 전사 밖 소리가 있는지 확인하는 단서입니다."],
    placement: "top",
  },
  {
    id: "batch-audio-controls",
    workspaceId: "batch",
    target: '[data-app-tour-target="batch-audio-header-controls"]',
    focusPanelId: "batch-audio",
    title: "Align 외 구간 재생",
    caption: "Script",
    description: "이 토글은 전사에 맞지 않는 구간을 재생할지, 정렬된 구간만 들을지 바꿉니다. 누락 발화를 찾을 때 중요합니다.",
    bullets: ["꺼두면 정렬 밖 구간은 무음처럼 처리되어 전사 확인에 집중할 수 있습니다.", "켜두면 전사에서 빠진 숨소리나 말소리를 찾기 쉽습니다."],
    placement: "top",
  },
  {
    id: "batch-audio",
    workspaceId: "batch",
    target: '[data-app-tour-panel-id="batch-audio"]',
    title: "듣고 바로 고치기",
    caption: "Script",
    description: "오디오 카드는 선택 행을 재생하고, 타임라인에서 누른 단어 위치로 이동합니다. 전사 오류를 귀로 확인한 뒤 표에서 바로 수정합니다.",
    bullets: ["타임라인과 재생 카드가 같은 syncKey로 연결되어 위치가 맞춰집니다.", "파형 우클릭 편집은 전사 검수용 짧은 샘플을 만들 때 쓸 수 있습니다."],
    placement: "top",
  },
  {
    id: "batch-right",
    workspaceId: "batch",
    target: { selectors: '[data-app-tour-panel-region="right"]', strategy: "all" },
    title: "화자와 Script 설정",
    caption: "Script",
    description: "오른쪽 영역은 화자 선택과 Whisper, WordAlign, DiariZen 설정을 한 묶음으로 관리합니다. 화자 토글은 표에 보이는 행과 내보내기 후보에 영향을 줍니다.",
    bullets: ["화자 구분 Run은 전사 결과가 있는 상태에서 화자 목록을 만듭니다.", "WordAlign 낮은 점수 기준은 타임라인의 확인필요 판정과 연결됩니다."],
    placement: "left",
  },
  {
    id: "training-browser",
    workspaceId: "training",
    target: '[data-app-tour-panel-id="training-browser"]',
    title: "학습 데이터와 결과 폴더",
    caption: "Training",
    description: "Training 브라우저는 학습 manifest나 dataset 파일, 그리고 생성된 체크포인트 폴더를 함께 봅니다.",
    bullets: ["입력은 학습 데이터셋, 출력은 weights와 logs를 확인하는 위치입니다.", "체크포인트 폴더를 고르면 오른쪽 설정의 모델 목록과 연결됩니다."],
    placement: "right",
  },
  {
    id: "training-version",
    workspaceId: "training",
    target: '[data-app-tour-target="training-version-control"]',
    title: "GPT-SoVITS 버전 선택",
    caption: "Training",
    description: "학습 옵션 상단의 버전 선택은 GPT-SoVITS v1, v2, v3, v4, Pro 계열에 맞는 기본 pretrained 경로와 학습 옵션을 맞춥니다.",
    bullets: ["버전을 바꾸면 중앙 계획과 오른쪽 pretrained 기본값이 같이 바뀔 수 있습니다.", "v3/v4 계열은 LoRA rank 같은 다른 옵션이 나타납니다."],
    placement: "top",
  },
  {
    id: "training-plan",
    workspaceId: "training",
    target: '[data-app-tour-panel-id="training-plan"]',
    title: "학습 계획",
    caption: "Training",
    description: "중앙 학습 옵션은 배치 크기, epoch, 저장 주기, LoRA rank, DPO 같은 학습 단위를 정합니다. 모델별로 보이는 필드가 달라집니다.",
    bullets: ["저장 주기가 너무 길면 중간 체크포인트 복구가 어렵습니다.", "배치 크기는 GPU 메모리와 학습 속도의 균형입니다."],
    placement: "top",
  },
  {
    id: "training-results",
    workspaceId: "training",
    target: '[data-app-tour-panel-id="training-results"]',
    title: "체크포인트 결과 표",
    caption: "Training",
    description: "결과 표에는 stage, epoch, step, elapsed, checkpoint 경로가 쌓입니다. 완료된 체크포인트는 Inference의 checkpoint 후보가 됩니다.",
    bullets: ["행을 고르면 브라우저와 선택 경로가 해당 체크포인트로 맞춰집니다.", "학습 중에는 이 표와 공통 콘솔 로그를 함께 봅니다."],
    placement: "top",
  },
  {
    id: "training-tensorboard-button",
    workspaceId: "training",
    target: '[data-app-tour-target="table-toolbar-training"]',
    title: "TensorBoard 버튼",
    caption: "Training",
    description: "학습 결과 표 오른쪽 버튼은 TensorBoard 그래프 위젯을 엽니다. loss 변화나 학습 진행 곡선을 확인할 때 쓰는 도구입니다.",
    bullets: ["실제 실행에서는 백엔드가 TensorBoard 세션을 띄웁니다.", "가이드에서는 네트워크나 프로세스를 시작하지 않고 화면 구조만 보여줍니다."],
    placement: "top",
  },
  {
    id: "training-tensorboard-dialog",
    workspaceId: "training",
    target: '[data-app-tour-target="training-tensorboard-dialog"]',
    title: "TensorBoard 위젯",
    caption: "Training",
    description: "이 위젯은 선택 모델의 로그 디렉터리를 기준으로 그래프를 표시합니다. 로그 경로가 없거나 실행 실패하면 에러와 로그 위치가 표시됩니다.",
    bullets: ["loss가 갑자기 튀면 데이터셋, 배치, 학습률을 다시 확인하세요.", "학습이 끝난 뒤에도 저장된 logdir 기준으로 다시 열 수 있습니다."],
    placement: "bottom",
  },
  {
    id: "training-right",
    workspaceId: "training",
    target: { selectors: '[data-app-tour-panel-region="right"]', strategy: "all" },
    title: "모델 선택과 경로 설정",
    caption: "Training",
    description: "오른쪽 영역은 GPT-SoVITS와 OmniVoice 선택, tool root, 모델명, GPU, pretrained 경로를 관리합니다. 실제 실행 스크립트에 넘기는 핵심 값입니다.",
    bullets: ["모델 선택을 바꾸면 중앙 학습 계획도 해당 모델용으로 바뀝니다.", "모델명은 출력 폴더와 체크포인트 자동 선택의 기준입니다."],
    placement: "left",
  },
  {
    id: "inference-browser",
    workspaceId: "inference",
    target: '[data-app-tour-panel-id="inference-browser"]',
    title: "레퍼런스 브라우저",
    caption: "Inference",
    description: "Inference는 레퍼런스 음성과 텍스트를 바탕으로 새 문장을 합성합니다. 왼쪽에서 음성을 고르면 중앙 레퍼런스 카드가 갱신됩니다.",
    bullets: ["입력 폴더는 prompt 음성과 참고 텍스트를 준비하는 곳입니다.", "출력 폴더에는 생성된 wav 결과가 쌓입니다."],
    placement: "right",
  },
  {
    id: "inference-run-mode",
    workspaceId: "inference",
    target: '[data-app-tour-target="inference-batch-mode-toggle"]',
    title: "단일/일괄 추론",
    caption: "Inference",
    description: "브라우저 상단의 모드는 하나의 레퍼런스로 합성할지, 여러 레퍼런스를 체크해 일괄 추론할지 정합니다.",
    bullets: ["일괄 추론에서는 파일 목록의 체크박스가 batchReferenceAudioPaths가 됩니다.", "단일 추론은 선택된 한 레퍼런스와 중앙 입력값에 집중합니다."],
    placement: "right",
  },
  {
    id: "inference-multi-reference",
    workspaceId: "inference",
    target: '[data-app-tour-target="inference-multi-reference-button"]',
    title: "다중 참고 오디오",
    caption: "Inference",
    description: "GPT-SoVITS 모드에서는 레퍼런스 카드 상단 버튼으로 다중 참고 오디오 목록을 열 수 있습니다. 보조 레퍼런스를 추가해 목소리 안정성을 보강합니다.",
    bullets: ["버튼을 누르면 레퍼런스 대사 입력 대신 선택된 보조 오디오 목록이 보입니다.", "OmniVoice나 다른 모드에서는 이 버튼이 숨겨질 수 있습니다."],
    placement: "top",
  },
  {
    id: "inference-reference",
    workspaceId: "inference",
    target: '[data-app-tour-target="inference-transcript-card-reference"]',
    title: "레퍼런스 음성과 대사",
    caption: "Inference",
    description: "레퍼런스 카드는 목소리 기준 음성과 그 음성의 실제 대사를 함께 담습니다. zero-shot 합성에서는 이 둘의 일치도가 품질을 크게 좌우합니다.",
    bullets: ["짧고 깨끗한 레퍼런스가 안정적입니다.", "텍스트는 실제 발화와 최대한 일치해야 합니다."],
    placement: "top",
  },
  {
    id: "inference-output",
    workspaceId: "inference",
    target: '[data-app-tour-target="inference-transcript-card-output"]',
    title: "합성 문장과 결과",
    caption: "Inference",
    description: "출력 카드는 합성할 문장을 입력하고, 실행 후 생성된 결과 음성을 들어보는 곳입니다. 긴 문장은 설정의 text split 방식에 따라 나뉩니다.",
    bullets: ["결과가 생성되면 출력 오디오와 결과 표가 함께 채워집니다.", "문장 길이가 길수록 분할 방식과 언어 설정을 확인하세요."],
    placement: "top",
  },
  {
    id: "inference-results",
    workspaceId: "inference",
    target: '[data-app-tour-panel-id="inference-results"]',
    title: "추론 실행 기록",
    caption: "Inference",
    description: "결과 표는 어떤 모델, 모드, checkpoint, 레퍼런스로 어떤 출력이 만들어졌는지 기록합니다. 여러 후보를 비교할 때 기준표가 됩니다.",
    bullets: ["행을 선택하면 출력 오디오 카드가 해당 결과로 이동합니다.", "EXPORT는 최종 결과 wav를 작업 폴더 밖으로 정리합니다."],
    placement: "top",
  },
  {
    id: "inference-right",
    workspaceId: "inference",
    target: { selectors: '[data-app-tour-panel-region="right"]', strategy: "all" },
    title: "합성 모델과 세부 옵션",
    caption: "Inference",
    description: "오른쪽 영역은 GPT-SoVITS와 OmniVoice 선택, checkpoint 모드, 언어, temperature, top P 같은 합성 옵션을 관리합니다.",
    bullets: ["checkpoint 모드는 Training 결과를 불러와 같은 목소리를 재사용합니다.", "temperature와 top P는 안정성과 다양성의 균형을 바꿉니다."],
    placement: "left",
  },
] satisfies readonly AppGuideTourStep[];

export type AppGuideStepId = (typeof appTourSteps)[number]["id"];
