export type { AppGuideTourStep } from "./app-tour-types";
import type { AppGuideTourStep } from "./app-tour-types";

export const appTourSteps = [
  {
    id: "guide-entry",
    workspaceId: "overview",
    target: '[data-app-tour-target="guide-button"]',
    title: "가이드 모드 시작",
    caption: "공통",
    description: "가이드를 여는 동안 실제 작업 데이터는 그대로 두고, 화면에는 가이드용 샘플 프로젝트만 임시로 보여줍니다. 닫으면 원래 화면으로 즉시 돌아갑니다.",
    bullets: ["샘플 파일, 표, 오른쪽 위젯, 터미널 로그는 가이드 전용입니다.", "아래 버튼이나 표를 눌러도 실제 실행 상태는 바뀌지 않습니다."],
    placement: "right",
  },
  {
    id: "workspace-nav",
    workspaceId: "overview",
    target: '[data-app-tour-target="workspace-nav"]',
    title: "작업 페이지 이동",
    caption: "공통",
    description: "왼쪽 탭은 전체 파이프라인의 단계입니다. Slice에서 자르고, Tagging과 Speaker로 품질 정보를 만들고, Overview와 Batch QC로 검수한 뒤 Training과 Inference로 이어집니다.",
    bullets: ["가이드 중에는 단계에 맞춰 페이지가 자동으로 바뀝니다.", "실제 선택된 작업 페이지는 가이드 종료 후 복원됩니다."],
    placement: "right",
  },
  {
    id: "run-controls",
    workspaceId: "overview",
    target: '[data-app-tour-target="run-controls"]',
    title: "실행과 내보내기",
    caption: "공통",
    description: "NEW RUN은 현재 페이지의 입력을 처리하고, EXPORT는 체크된 결과를 내보냅니다. 이 영역의 상태 텍스트는 현재 작업이 멈춰 있는지, 실행 중인지 빠르게 알려줍니다.",
    bullets: ["RETRY는 실패한 실행을 이어가거나 같은 조건으로 다시 실행할 때 사용합니다.", "GUIDE는 지금 보는 단계별 샘플 화면을 다시 열 때 씁니다."],
    placement: "right",
  },
  {
    id: "slice-browser",
    workspaceId: "slice",
    target: '[data-app-tour-panel-id="slice-browser"]',
    title: "입력 파일을 고르는 곳",
    caption: "Slice",
    description: "Slice는 긴 WAV를 작업 가능한 조각으로 나누는 시작점입니다. 가이드 샘플에서는 input 폴더에 원본 음성 3개가 들어온 상태부터 보여줍니다.",
    bullets: ["파일을 선택하면 파형 편집 카드와 결과 표가 같은 원본을 바라봅니다.", "출력 폴더는 자른 조각이 저장될 위치입니다."],
    placement: "right",
  },
  {
    id: "slice-editor",
    workspaceId: "slice",
    target: '[data-app-tour-panel-id="slice-editor"]',
    title: "파형에서 구간 다듬기",
    caption: "Slice",
    description: "다음 단계에서는 선택한 음성이 파형 카드에 들어오고, 자동 분할된 구간이 준비됩니다. 여기서 앞뒤 여백을 줄이거나, 구간을 합치고 나누는 흐름을 확인합니다.",
    bullets: ["선택한 행과 파형 선택 영역은 서로 따라갑니다.", "구간 편집 결과는 표와 출력 브라우저에 반영됩니다."],
    placement: "top",
  },
  {
    id: "slice-table",
    workspaceId: "slice",
    target: '[data-app-tour-panel-id="slice-results"]',
    title: "조각 결과 확인",
    caption: "Slice",
    description: "결과 표에는 각 조각의 시작, 종료, 길이, 마커 수, 출력 경로가 쌓입니다. 체크박스로 내보낼 조각만 남길 수 있습니다.",
    bullets: ["행을 선택하면 왼쪽 브라우저와 파형이 해당 조각으로 이동합니다.", "검색은 파일명이나 상태만 빠르게 좁힐 때 씁니다."],
    placement: "top",
  },
  {
    id: "slice-settings",
    workspaceId: "slice",
    target: '[data-app-tour-panel-id="slice-settings"]',
    title: "분할 기준 조정",
    caption: "Slice",
    description: "오른쪽 설정은 침묵 길이, 패딩, 최대 조각 길이처럼 분할 결과를 바꾸는 값입니다. 같은 파일이라도 이 값에 따라 표의 조각 수가 달라집니다.",
    bullets: ["너무 잘게 쪼개지면 최소 이벤트 길이와 병합 간격을 올립니다.", "앞뒤 말소리가 잘리면 speech pad와 boundary search 값을 조정합니다."],
    placement: "left",
  },
  {
    id: "tagging-browser",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-browser"]',
    title: "태깅할 음성 묶음",
    caption: "Tagging",
    description: "Tagging은 Pretrained SED 기반으로 잡음, 웃음, 숨소리 같은 이벤트를 찾아 검수 힌트로 붙입니다. 가이드에서는 Slice 결과 일부가 입력으로 들어온 상태를 보여줍니다.",
    bullets: ["왼쪽 파일을 고르면 재생 카드와 표 선택이 함께 이동합니다.", "체크 해제한 파일은 내보내기에서 제외됩니다."],
    placement: "right",
  },
  {
    id: "tagging-audio",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-audio"]',
    title: "태그를 들으며 확인",
    caption: "Tagging",
    description: "오디오 재생 카드는 표에서 선택한 행을 바로 들어보는 곳입니다. 의심 태그가 붙은 구간은 이 카드에서 소리를 확인하고 판단합니다.",
    bullets: ["잘못 잡힌 태그는 오른쪽 점수 기준에서 완화할 수 있습니다.", "자르기 편집은 원본을 해치지 않는 편집 세션으로 관리됩니다."],
    placement: "bottom",
  },
  {
    id: "tagging-schema",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-queue"]',
    title: "태그 스키마와 기준",
    caption: "Tagging",
    description: "스키마 카드는 어떤 태그가 NG로 취급되는지 보여줍니다. 가이드 샘플은 breath와 noise를 검수 후보로 잡아 둔 상태입니다.",
    bullets: ["점수 컷을 바꾸면 결과 표의 NG 판단도 같이 바뀝니다.", "프로젝트별로 민감한 태그만 따로 남길 수 있습니다."],
    placement: "top",
  },
  {
    id: "tagging-table",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-results"]',
    title: "태깅 결과 표",
    caption: "Tagging",
    description: "결과 표에는 파일별 NG 태그와 상태가 표시됩니다. 이 표는 이후 Overview나 Batch QC에서 검수 우선순위를 정하는 데 쓰입니다.",
    bullets: ["NG 태그 셀은 중요한 태그를 짧게 요약합니다.", "행 선택은 재생 카드와 파일 브라우저를 같은 파일로 맞춥니다."],
    placement: "top",
  },
  {
    id: "tagging-settings",
    workspaceId: "tagging",
    target: '[data-app-tour-panel-id="tagging-settings"]',
    title: "모델과 점수 기준",
    caption: "Tagging",
    description: "오른쪽 설정에서는 SED 모델, threshold, median window, top K 같은 판정 기준을 바꿉니다. 샘플 데이터는 기준이 바뀌면 표가 어떻게 해석되는지 보이도록 구성했습니다.",
    bullets: ["민감도를 낮추면 사소한 숨소리나 클릭음이 줄어듭니다.", "검수 목적이 엄격하면 threshold를 낮춰 더 많이 잡습니다."],
    placement: "left",
  },
  {
    id: "speaker-browser",
    workspaceId: "speaker",
    target: '[data-app-tour-panel-id="speaker-browser"]',
    title: "화자 개선 입력",
    caption: "Speaker",
    description: "Speaker 페이지는 원본과 개선 결과를 나란히 비교합니다. 왼쪽에서는 처리할 원본과 생성된 결과 파일을 오가며 선택합니다.",
    bullets: ["입력은 원본, 출력은 모델이 만든 개선 음성입니다.", "표에서 행을 고르면 두 플레이어가 같은 파일 쌍으로 맞춰집니다."],
    placement: "right",
  },
  {
    id: "speaker-progress",
    workspaceId: "speaker",
    target: '[data-app-tour-panel-id="speaker-progress"]',
    title: "처리 진행 표",
    caption: "Speaker",
    description: "진행 표는 파일별 모델, 상태, 실패 여부를 보여줍니다. 샘플에서는 Sidon 처리 2건과 검토가 필요한 1건을 넣었습니다.",
    bullets: ["실패한 행은 RETRY로 다시 처리할 수 있습니다.", "상태가 완료된 행은 오디오 비교 카드에서 바로 확인합니다."],
    placement: "top",
  },
  {
    id: "speaker-audio",
    workspaceId: "speaker",
    target: '[data-app-tour-panel-id="speaker-audio"]',
    title: "원본과 결과 비교",
    caption: "Speaker",
    description: "오디오 비교 카드는 원본 음성과 결과 음성을 같은 행 기준으로 들려줍니다. 모델을 바꿔 실행했을 때 음색 손상이나 잡음 감소를 이곳에서 판단합니다.",
    bullets: ["양쪽 재생 위치를 맞춰 짧은 구간을 반복 비교합니다.", "결과가 마음에 들지 않으면 오른쪽 모델 설정을 바꿔 재실행합니다."],
    placement: "top",
  },
  {
    id: "speaker-right",
    workspaceId: "speaker",
    target: { selectors: '[data-app-tour-panel-region="right"]', strategy: "all" },
    title: "모델 선택과 상세 설정",
    caption: "Speaker",
    description: "오른쪽 두 카드는 함께 한 묶음입니다. 위 카드에서 Sidon, Resemble, VoiceFixer를 고르고 아래 카드에서 선택 모델의 세부 옵션을 조정합니다.",
    bullets: ["가이드는 오른쪽 영역 전체를 한 번에 잡아 위아래 카드가 잘리지 않게 보여줍니다.", "선택 모델에 따라 아래 설정 폼이 달라집니다."],
    placement: "left",
  },
  {
    id: "overview-table",
    workspaceId: "overview",
    target: '[data-app-tour-panel-id="overview-results"]',
    title: "프로젝트 QC 표",
    caption: "Overview",
    description: "결과 표는 프로젝트 전체 파일의 길이, 샘플레이트, 노이즈 점수, 상태를 보여줍니다. 여기서 문제 파일을 골라 재생하거나 내보내기 제외를 결정합니다.",
    bullets: ["컬럼 메뉴로 점수 기준을 빠르게 바꿀 수 있습니다.", "행을 고르면 아래 오디오 재생과 오른쪽 상세 카드가 같은 파일을 봅니다."],
    placement: "top",
  },
  {
    id: "overview-audio",
    workspaceId: "overview",
    target: '[data-app-tour-panel-id="overview-audio"]',
    title: "문제 구간 재생",
    caption: "Overview",
    description: "오디오 재생 카드는 Overview 표에서 고른 파일을 들려줍니다. 수치만으로 애매한 파일은 이곳에서 바로 귀로 확인합니다.",
    bullets: ["필요하면 짧은 구간을 잘라 검수 메모용으로 확인합니다.", "선택 행이 바뀌면 재생 카드도 자동으로 바뀝니다."],
    placement: "top",
  },
  {
    id: "overview-right",
    workspaceId: "overview",
    target: { selectors: '[data-app-tour-panel-region="right"]', strategy: "all" },
    title: "분석 모듈과 상세값",
    caption: "Overview",
    description: "오른쪽 위젯은 분석 모듈 선택과 선택 파일의 상세값을 나눠 보여줍니다. 위아래 카드가 모두 한 기능 흐름이므로 가이드도 전체 영역을 잡습니다.",
    bullets: ["모듈 카드에서는 노이즈 분석 사용 여부를 조정합니다.", "상세 카드는 선택한 행의 원본 경로와 점수 원값을 확인하는 곳입니다."],
    placement: "left",
  },
  {
    id: "batch-table",
    workspaceId: "batch",
    target: '[data-app-tour-panel-id="batch-table"]',
    title: "전사 편집 표",
    caption: "Batch QC",
    description: "표에서는 자동 전사와 편집 전사를 나란히 보고 수정합니다. 가이드 샘플에는 한 문장의 단어 alignment가 이미 들어 있어 타임라인과 연결됩니다.",
    bullets: ["자동 전사 셀의 색상 토큰은 신뢰도와 누락 구간을 보여줍니다.", "편집 전사를 바꾸면 내보내기 데이터셋에도 반영됩니다."],
    placement: "top",
  },
  {
    id: "batch-timeline",
    workspaceId: "batch",
    target: '[data-app-tour-panel-id="batch-timeline"]',
    title: "단어 단위 타임라인",
    caption: "Batch QC",
    description: "타임라인은 단어별 시작, 종료, score, 메모를 보여줍니다. 낮은 점수나 누락 구간을 눌러 바로 그 시간으로 이동할 수 있습니다.",
    bullets: ["점수가 낮은 단어는 검토 후보입니다.", "빈 구간은 transcript 밖 음성을 찾는 데 도움이 됩니다."],
    placement: "top",
  },
  {
    id: "batch-audio",
    workspaceId: "batch",
    target: '[data-app-tour-panel-id="batch-audio"]',
    title: "듣고 바로 고치기",
    caption: "Batch QC",
    description: "오디오 카드에서는 선택 행을 재생하면서 전사와 align 구간을 확인합니다. 타임라인에서 누른 단어 위치로 재생 헤드가 이동합니다.",
    bullets: ["Align 밖 구간 재생 옵션으로 전사에 빠진 소리를 찾습니다.", "짧은 미리듣기로 문제 단어만 반복 확인할 수 있습니다."],
    placement: "top",
  },
  {
    id: "batch-right",
    workspaceId: "batch",
    target: { selectors: '[data-app-tour-panel-region="right"]', strategy: "all" },
    title: "화자와 Batch 설정",
    caption: "Batch QC",
    description: "오른쪽에는 화자 선택 위젯과 Whisper, WordAlign, DiariZen 설정이 있습니다. 화자 필터는 표에 보이는 행과 내보내기 후보를 같이 정리합니다.",
    bullets: ["화자 토글을 끄면 해당 화자의 행이 표에서 숨겨집니다.", "모델 설정은 다음 실행부터 적용됩니다."],
    placement: "left",
  },
  {
    id: "training-browser",
    workspaceId: "training",
    target: '[data-app-tour-panel-id="training-browser"]',
    title: "학습 데이터와 체크포인트",
    caption: "Training",
    description: "Training은 데이터셋 파일과 학습 결과 체크포인트를 함께 관리합니다. 가이드 샘플은 manifest와 이전 checkpoint가 있는 상태를 보여줍니다.",
    bullets: ["입력은 학습용 manifest나 dataset 폴더입니다.", "출력은 생성된 weights와 logs를 확인하는 영역입니다."],
    placement: "right",
  },
  {
    id: "training-plan",
    workspaceId: "training",
    target: '[data-app-tour-panel-id="training-plan"]',
    title: "학습 계획 조정",
    caption: "Training",
    description: "중앙 학습 옵션에서는 배치 크기, epoch, 저장 주기, LoRA rank 같은 실제 학습 단위를 정합니다. 선택 모델과 GPT 버전에 따라 폼이 바뀝니다.",
    bullets: ["상단 버전 선택은 GPT-SoVITS 기본 pretrained 경로와 옵션을 맞춥니다.", "샘플은 v2, 8 epoch, 4 epoch마다 저장하는 구성입니다."],
    placement: "top",
  },
  {
    id: "training-results",
    workspaceId: "training",
    target: '[data-app-tour-panel-id="training-results"]',
    title: "학습 결과 추적",
    caption: "Training",
    description: "결과 표에는 stage, epoch, step, elapsed, checkpoint가 쌓입니다. 학습 중에는 이 표와 터미널 로그가 함께 갱신됩니다.",
    bullets: ["완료된 checkpoint는 Inference 페이지의 checkpoint 선택 후보가 됩니다.", "TensorBoard 버튼으로 로그 그래프를 별도 창에서 열 수 있습니다."],
    placement: "top",
  },
  {
    id: "training-right",
    workspaceId: "training",
    target: { selectors: '[data-app-tour-panel-region="right"]', strategy: "all" },
    title: "모델 선택과 학습 설정",
    caption: "Training",
    description: "오른쪽은 GPT-SoVITS와 OmniVoice 중 어떤 학습기를 쓸지, 그리고 tool root와 pretrained 경로를 관리하는 곳입니다.",
    bullets: ["위 카드에서 모델을 바꾸면 중앙 계획과 아래 설정이 같이 바뀝니다.", "아래 카드의 경로 값은 실행 스크립트에 전달됩니다."],
    placement: "left",
  },
  {
    id: "training-terminal",
    workspaceId: "training",
    target: '[data-app-tour-target="workspace-terminal-widget"]',
    title: "학습 로그 확인",
    caption: "Training",
    description: "터미널 위젯은 백엔드 실행 로그를 짧게 보여줍니다. 긴 로그는 화살표 버튼으로 전체 터미널 다이얼로그를 열어 확인합니다.",
    bullets: ["가이드 샘플에서는 epoch 저장과 checkpoint 생성 로그를 순서대로 보여줍니다.", "실제 실행 중 실패하면 이곳에서 에러 원인을 가장 먼저 봅니다."],
    placement: "left",
    terminalOpen: true,
  },
  {
    id: "inference-browser",
    workspaceId: "inference",
    target: '[data-app-tour-panel-id="inference-browser"]',
    title: "레퍼런스 음성 선택",
    caption: "Inference",
    description: "Inference는 학습한 목소리로 새 문장을 합성하는 페이지입니다. 왼쪽에서 레퍼런스 음성을 고르면 중앙 레퍼런스 카드에 바로 들어갑니다.",
    bullets: ["입력 폴더는 prompt 음성과 참고 텍스트를 준비하는 곳입니다.", "출력 폴더에는 합성된 결과 wav가 쌓입니다."],
    placement: "right",
  },
  {
    id: "inference-reference",
    workspaceId: "inference",
    target: '[data-app-tour-panel-id="inference-reference"]',
    title: "레퍼런스와 프롬프트",
    caption: "Inference",
    description: "레퍼런스 카드는 목소리 기준이 되는 음성과 그 음성의 텍스트를 함께 담습니다. zero-shot 모드에서는 이 정보가 합성 품질을 크게 좌우합니다.",
    bullets: ["짧고 깨끗한 레퍼런스일수록 안정적입니다.", "텍스트는 실제 발화와 최대한 일치해야 합니다."],
    placement: "top",
  },
  {
    id: "inference-right",
    workspaceId: "inference",
    target: { selectors: '[data-app-tour-panel-region="right"]', strategy: "all" },
    title: "합성 모델과 세부 옵션",
    caption: "Inference",
    description: "오른쪽은 GPT-SoVITS와 OmniVoice 선택, checkpoint 모드, 언어, 샘플링 값을 조정하는 영역입니다. 학습 결과를 연결하는 중심 위젯입니다.",
    bullets: ["checkpoint 모드는 Training 결과를 불러와 같은 목소리를 재사용합니다.", "temperature와 top P는 발화 안정성과 다양성의 균형을 바꿉니다."],
    placement: "left",
  },
  {
    id: "inference-output",
    workspaceId: "inference",
    target: '[data-app-tour-panel-id="inference-output"]',
    title: "합성할 문장과 결과 음성",
    caption: "Inference",
    description: "출력 카드는 합성할 문장을 입력하고, 실행 후 생성된 음성을 들어보는 곳입니다. 가이드 샘플은 이미 한 번 실행된 결과를 보여줍니다.",
    bullets: ["긴 문장은 text split 설정에 따라 나뉘어 처리됩니다.", "결과가 만들어지면 출력 오디오와 결과 표가 함께 채워집니다."],
    placement: "top",
  },
  {
    id: "inference-table",
    workspaceId: "inference",
    target: '[data-app-tour-panel-id="inference-results"]',
    title: "추론 실행 기록",
    caption: "Inference",
    description: "추론 결과 표는 어떤 모델과 모드로 어떤 레퍼런스를 사용했는지 기록합니다. 여러 후보를 뽑아 비교할 때 이 표가 기준표 역할을 합니다.",
    bullets: ["행을 선택하면 출력 오디오 카드가 해당 결과로 이동합니다.", "EXPORT로 최종 결과 음성을 작업 폴더 밖으로 정리할 수 있습니다."],
    placement: "top",
  },
  {
    id: "inference-terminal",
    workspaceId: "inference",
    target: '[data-app-tour-target="workspace-terminal-widget"]',
    title: "추론 로그와 실패 원인",
    caption: "Inference",
    description: "Inference 실행 로그도 같은 터미널 위젯에서 확인합니다. checkpoint 누락, GPU 설정, 텍스트 언어 오류처럼 표에 다 담기지 않는 원인은 로그가 가장 정확합니다.",
    bullets: ["가이드 샘플은 모델 로드, 문장 분할, wav 저장 흐름을 짧게 보여줍니다.", "문제가 생기면 전체 터미널에서 명령과 로그 파일 경로를 확인합니다."],
    placement: "left",
    terminalOpen: true,
  },
] satisfies readonly AppGuideTourStep[];

export type AppGuideStepId = (typeof appTourSteps)[number]["id"];
